<audio id="notif_audio"><source src="<?php echo PUBLIC_PATH.'sounds/notify.ogg';?>" type="audio/ogg"><source src="<?php echo PUBLIC_PATH.'sounds/notify.mp3';?>" type="audio/mpeg"><source src="<?php echo PUBLIC_PATH.'sounds/notify.wav';?>" type="audio/wav"></audio>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div id="new-message-notif"></div>
    <h3 class="text-center">Mensajes</h3>
    <table class="table">
      <thead>
        <tr>
          <td>Nombre</td>
          <td>Mensaje</td>
        </tr>
      </thead>
      <tbody id="cuerpoMensaje">
        <?php foreach($mensajes as $key => $mensaje): ?>
          <tr>
            <td><?php echo $mensaje->nombre ?></td>
            <td><?php echo $mensaje->mensaje ?></td>
          </tr>
        <?php endforeach ?>
      </tbody>
    </table>
  </div>
  <div class="col-md-3"></div>
</div>
<script type="text/javascript">
var socket = io.connect( 'http://'+window.location.hostname+':3000' );

socket.on( 'new_message', function( data ) {
    $('#notif_audio')[0].play();
    $.notify("Nuevo mensaje", "success");
    $( "#cuerpoMensaje" ).prepend('<tr><td>'+data.nombre+'</td><td>'+data.mensaje+'</td></tr>');
    //$( "#no-message-notif" ).html('');
});
</script>
